# HEMTT pre v1
name = "CBA_A3"
prefix = "cba"
mainprefix = "x"
author = "CBATeam"
mainprefix = "x"
files = [
    "mod.cpp",
    "README.md",
    "LICENSE.md",
    "logo_cba_ca.paa",
    "meta.cpp",
    "userconfig"
]
