[default]

dlc = []
optionals = []

parameters = [
    "-window",
    "-noPause",
    "-noPauseAudio",
]

[VR]
extends = "default"
mission = "Test.VR"

workshop = [
    "2369477168", # Advanced Developer Tools
]