[sqf.banned_commands]
options.ignore = [
    "addPublicVariableEventHandler", # Alt syntax is broken, we are using main syntax
]

[sqf.var_all_caps]
options.ignore = [
    "SLX_*"
]

[sqf.undefined]
enabled = true
options.check_orphan_code = false

[sqf.unused]
enabled = false
options.check_params = false

[sqf.shadowed]
enabled = false

[sqf.not_private]
enabled = false
